// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL3Zoq51oVVXbKpYg6vbOduG2p2q7Eqb4',
    appId: '1:808843995745:web:9714bf5be83b2fa4165820',
    messagingSenderId: '808843995745',
    projectId: 'pachanga-f34f0',
    authDomain: 'pachanga-f34f0.firebaseapp.com',
    storageBucket: 'pachanga-f34f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAow1MxVC-wC1wG550CmYSTWzAwHazpR3M',
    appId: '1:808843995745:android:effb598facb78ff5165820',
    messagingSenderId: '808843995745',
    projectId: 'pachanga-f34f0',
    storageBucket: 'pachanga-f34f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoeQK5c4DZ9ihomSw1keISLjjgvv3UBtM',
    appId: '1:808843995745:ios:89b8356703a914f2165820',
    messagingSenderId: '808843995745',
    projectId: 'pachanga-f34f0',
    storageBucket: 'pachanga-f34f0.firebasestorage.app',
    iosBundleId: 'com.example.pachanga',
  );
}
